name: Format (prettier)

on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - "**.sol"
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install
        run: npm install  --save-dev prettier prettier-plugin-solidity
        env:
          CI: true

      - name: Run prettier
        run: npx prettier --check 'src/**/*.sol'
