name: Slither Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v16

      - name: Configure Cachix
        uses: cachix/cachix-action@v10
        with:
          name: dapp

      - name: export remappings
        run: export DAPP_REMAPPINGS=$(cat remappings.txt)

      - name: rm test files
        run: rm -rf src/test

      - name: Install solc
        run: nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions.solc_0_8_11

      - name: Install dependencies
        run: nix-shell --run 'dapp update'

      - name: Get remappings
        id: vars
        run: echo ::set-output name=remaps::$(cat remappings.txt)

      - name: Build the contracts
        run: nix-shell --run 'dapp build'
        env:
          DAPP_REMAPPINGS: steps.vars.outputs.remaps

      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        with:
          ignore-compile: true
